// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import OffcanvasController from "./offcanvas_controller"
application.register("offcanvas", OffcanvasController)

import ReportController from "./report_controller"
application.register("report", ReportController)
